name: goal_networking_app
description: A goal-based networking application to connect users and help them achieve their goals.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.1.1
  mobile_scanner: ^5.2.3
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.1.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  share_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - .env
